### ISSUE TITLE
服务已启动但无法使用

### ISSUE THREAD

**Issue by yuk7778** [zmecust/Vue-WebRTC2.0#1]
我已经配置好线上环境和反向代理了，能正常连上网站，但是打好昵称后按下创建昵称却没有反应
server.js有正常运作
有使用SSL連線

**Comment by zmecust** [comment]
好的，我下午详细和你了解下，现在我在吃饭

From Min Zhang

**Comment by zmecust** [comment]
加我qq 247281377 这样效率高一点

From Min Zhang
